### ISSUE TITLE
change depnes to fibonacci-chain

### ISSUE THREAD

**Issue by Timwood0x10** [fibonacci-chain/core#4]
**Describe the Task**
![image](https://github.com/fibonacci-chain/core/assets/121157680/9eba84bc-40d7-4248-bcfa-51d38e579632)
As shown in the figure above, the code uses the sei-protocol dependency

**task list**
* [ ] change depens to fibonacci-chian
* [ ] opitmize init local chain shell 
* [ ] local build and setup chain succeccful
