### ISSUE TITLE
[Update] Fork and update sei protocol to fibonacci cain/core

### ISSUE THREAD

**Issue by China-Chris** [fibonacci-chain/core#6]
**Fork and update sei protocol to fibonacci cain/core**
Solving the dependency issue related to sei protocol in the core

**task list**
* [x] Update wasmd dependencies
* [x] Update iavl dependencies
* [x] Update db dependencies

**notet**
The relevant name needs to be forked to the Fibonacci chain warehouse and the name changed

**Comment by China-Chris** [comment]
make a copy for @fibonacciTeam     The relevant modifications have been completed, but I found that an additional pull was generated_ Request_ Template.md file. I am unable to delete this file. We need to take a look at this issue
